language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
before_install:
- pip install pytest pytest-cov
install:
- pip install -r requirements.txt
- pip install -e .
script: py.test ./tests/test_*.py --cov